services:
  symfony:
    build: .
    container_name: symfony_cli
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mariadb
    environment:
      DATABASE_URL: "mysql://symfony:symfony@mariadb:3306/symfony"
      PHP_MEMORY_LIMIT: "512M"
    command: tail -f /dev/null
    tty: true

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data: