services:
  symfony:
    build: .
    container_name: symfony_cli
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mariadb
      - redis
    environment:
      DATABASE_URL: "mysql://symfony:symfony@mariadb:3306/symfony"
      REDIS_URL: "redis://redis:6379"
    command: tail -f /dev/null
    tty: true

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
